[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "transferscore"
version = "0.0.1"
dependencies = [
    "numpy",
]

[tool.setuptools]
packages = ["transferscore"]
